### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by untotren** [MediaKraken/MediaKraken_Deployment#17]
There is nothing about what this does, how it works, how to install.  There is literally no information at all.

**Comment by SpootDev** [comment]
Website is back up with more info on the goals and how....but it's horribly out of date.  I'll work on that this weekend.

This app is still very pre-alpha.  Alot of the metadata is collected and media matched......but just recently started working hard on playback apps.

**Comment by SpootDev** [comment]
Added quite a bit more docs.  Still not great though.
