### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by michaelizer** [MediaKraken/MediaKraken_Deployment#38]
Hello, I just made a logo for your project, hope you liked it. 
![kraken2](https://user-images.githubusercontent.com/35619342/38845545-e8e83c56-41c5-11e8-83a0-18a4907aab6c.png)
![kraken1](https://user-images.githubusercontent.com/35619342/38845558-f622c67a-41c5-11e8-9039-4f056aa39bdb.png)
You can choose whatever color you want for any part of the logo, let me know if you liked it and I'll upload the files on a PR.

**Comment by SpootDev** [comment]
Neat!  I think the middle one could be a nice icon to use during spash screens/etc.

**Comment by michaelizer** [comment]
Glad you liked it, look at these.
![mk](https://user-images.githubusercontent.com/35619342/38972342-e089e218-436d-11e8-9598-3c5470091460.png)
![k](https://user-images.githubusercontent.com/35619342/38972350-e8cfad9a-436d-11e8-8a80-eb0210d74ab6.png)
Give me green light and I'll upload the files on a PR (including the logo type and their .svg version for scalability)

**Comment by SpootDev** [comment]
I think the middle one from the first set will do nicely.   Then with svg I should be able to scale to whatever is needed.

**Comment by michaelizer** [comment]
@SpootDev, done ([#41](https://github.com/MediaKraken/MediaKraken_Deployment/pull/41)), let me know if something's wrong (Y)

**Comment by SpootDev** [comment]
Merged
